---
services:
  bot:
    build:
      context: ./bot
    container_name: bot
    restart: unless-stopped
    env_file:
      - .env

  smb:
    image: dperson/samba
    container_name: smb
    restart: unless-stopped
    ports:
      - "445:445"
    environment:
      USER: "debug-user;debugforu"
      SHARE: "debugshare;/smbshare;yes;no;no;debug-user"
    volumes:
      - ./volumes/smb_data:/smbshare

  ssh:
    hostname: debug-cli
    build:
      context: ./ssh
    container_name: ssh
    restart: unless-stopped
    volumes:
      - ./volumes/ssh_data:/root/
    ports:
      - "2222:22"
    environment:
      - SSH_KEY_PATH=/home/debug-user/.ssh/authorized_keys
...
